In [2]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.random.rand(3,3)

array([[0.22924887, 0.14232372, 0.14714468],
       [0.00899627, 0.9642668 , 0.24097261],
       [0.75117117, 0.81508909, 0.14645105]])

In [9]:
np.random.seed(42)
np.random.randint(0,45,)

2