In [1]:
import numpy as np

In [2]:
#Create array of zeroes
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
#Create array of ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
#Create array of fives
5 * np.ones(10)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [5]:
#Create an array of integers from 10 to 50
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [7]:
#Array of even integers from 10 to 50
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
#3x3 matrix with values from 0 to 